spring.application.name=report-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/reports
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false

# Server Configuration
server.port=8080

# AWS Configuration
aws.access.key=${AWS_ACCESS_KEY:test-key}
aws.secret.key=${AWS_SECRET_KEY:test-secret}
aws.region=us-east-1

# SQS Configuration
aws.sqs.report-generation-queue=report-generation-queue
aws.sqs.status-update-queue=status-update-queue

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent-output=true

# Logging Configuration
logging.level.com.fiap.report=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
